name: Build and Package Application

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for fetching tags
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvnw.cmd clean package -Pdefault -Pall-in-one

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: packaged-app
        path: |
          target/*.jar
          target/*.war
          # Add more paths if needed
